# 股票配置文件
# market_type: A股-A, 港股-HK, 美股-US

stocks:
  - code: "600519"
    market_type: "A"
    name: "贵州茅台"
  
  - code: "00700"
    market_type: "HK"
    name: "腾讯控股"
  
  - code: "TSLA"
    market_type: "US"
    name: "特斯拉"